### ISSUE TITLE
Loan Return Preparation still broken

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#1001]
On a Mac
Build #352 
I am trying to remember what we decided the user should be able to do with this form. I created loans with and without uncataloged items. I was able to return items using the 'Return Loan' button on the form and that worked, but I was able to go back into 'Loan Return Preparation' and return more items than were originally loaned. 
Also, if I click on the 'Loan Return Preparation' form and return an item it is not updated in the Loan Preparations form. 

Did we decide that this would be for viewing only? If so then the bug would be that the '+' button needs to be removed from the Loan Return Preparation form.

<img width="1112" alt="Screen Shot 2021-07-26 at 5 39 39 PM" src="https://user-images.githubusercontent.com/61208178/127069950-b6937810-2276-4458-8f40-5a9b660848a8.png">

I was also able to return items without choosing an Agent - which is required.

**Comment by timo11** [comment]
commit 7a36223 above edits commonviews to make loanreturnpreparation read only. What to do about databased common views? 
Marking this fixed so the common views change can be tested, but maybe probably it's only partially fixed.

**Comment by timo11** [comment]
as of commit 05f2950, if for whatever reason the loanreturnpreparation form is editable, the '+' button will be unavailable (when clicked a msg informs the user that clicking is futile -- and the form usually becomes dysfunctional to reinforce the msg).
The '-' button still works.
Editing is still possible. I was unable to enter invalid quantities in the loanreturn dialog. But the lrp business rules might not update the quantity returned and resolved fields on the loanpreparation form, and users may have to update them to match the totals of the loanreturn preparations, otherwise they will be prevented from saving by the loanpreparation bus rules.

**Comment by tlammer** [comment]
- is not there.  When I click the Return Preparation button, I see this 
![image](https://user-images.githubusercontent.com/12532430/128079892-103e81a5-3c75-4b46-8707-0c2995738416.png)

**Comment by tlammer** [comment]
When I delete the return prep and try to save, I get an error that
![image](https://user-images.githubusercontent.com/12532430/128572177-e9fc3fad-a717-4ea6-b66d-b812b4f925da.png)

**Comment by timo11** [comment]
The quantity returned and quantity resolved fields should made editable. Even when the business rules "work", they can't update those fields when they are read-only.

**Comment by timo11** [comment]
Another possible fix is to make quantityreturned/resolved be uitype "dsptextfield" and remove the readonly attribute.

**Comment by timo11** [comment]
OK. Deleting loan return preps and editing lrp quantities can be done relatively safely, as long you don't try to cancel changes; and don't  repeatedly open, edit, and close the lrp form; and do not engage in other risky behaviors.

**Comment by tlammer** [comment]
the numbers aren't adding up correctly
![image](https://user-images.githubusercontent.com/12532430/129635447-6eac635d-adeb-4441-90d2-c1d02fa52c47.png)
