### ISSUE TITLE
Export Mappings with same name but different SpecifyUser will generate identical cache table names.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#1055]
And that would be very bad.  One user could overwrite a second user's data, and the other user could export the first user's data thinking it was their own.

**Comment by grantfitzsimmons** [comment]
Looks like this was solved in #1056

**Comment by melton-jason** [comment]
Can we confirm this is fixed? I don't see this as a database constraint when I checked them all in https://github.com/specify/specify7/issues/2924#issuecomment-1440638103. 

This might be fixed in Specify 6, but this does not seem to be unique to the database so could become a problem again in Specify 7.

**Comment by grantfitzsimmons** [comment]
@melton-jason We should open it as an issue on the 7 repo in that case
