### ISSUE TITLE
Agent Search doesn't search address fields

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#108]
Reported by Sweden:
The agent search window has agent and address fields available in the search window but when you enter data in the fields and click search, nothing happens - no error message pops up or in the error log, and no results are returned when there should be.

**Comment by timo11** [comment]
The problem occured because the search view def refers to the address fields as "addresses.PostalCode" for example, but the search query defined in search_config refers them without the "addresses" prefix. I changed the search_config query because changing the view def broke automatic labeling. However, changing search_config won't fix the bug for databases that contain customized express search configs. In those cases they will have to change the form or try to fix the resource associated with search_config.xml. (Also, the search dialogs for other tables are probably also broken, permit for example.)

**Comment by yvonneekanim** [comment]
Agents can be searched using address
