### ISSUE TITLE
Improve field descriptions

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1164]
We really need to improve our field descriptions.
Marking fields as unused or showing where they are used would be of great help.
I can compile a list of fields that are used by Sp7, which would be a good start. Then, we can either put those descriptions in place of the ones we have right now, or show them alongside the current ones in the database schema viewer

From Theresa:
> I believe `Taxon.visibility` was added when 6 was first created to allow for changes in the future but we did not implement the changes, so the field is superfluous. You will find it in more than just the taxon table

**Comment by grantfitzsimmons** [comment]
> > `latLongAccuracy` should be decisively labeled as unceratinty from the coordinates in meters or decimal degrees
> 
> The description is currently "radius -- in decimal degrees". Should it be updated to include "or meters"?

It should probably be meters or decimal degrees

**Comment by benanhalt** [comment]
Okay. I think I've fixed the things that were obvious errors. 

Updating all the user definable fields to have same description should probably done using an automated tool. 

The problem where the descriptions appear in other languages seems to stem from cases where there is only one language, PT say, in the descriptions. It seems like Specify 7 might be falling back to using that description if there is none in the selected language instead of using the field name. This seems like it could be a Specify 7 bug. We could go through and add descriptions for every field in every language even where it is the same as the field name, but that seems perverse.

Jason's other observations are mostly questions about what the descriptions of some fields should be. We should probably get input on those from Andy or Theresa.
