### ISSUE TITLE
Require java 8 for Specify 6.8.00 on macs

### ISSUE THREAD

**Issue by timo11** [specify/specify6#728]
see #613

**Comment by maxxxxxdlp** [comment]
I received the same error message when trying to open `Specify4GB` with:
Java 9
Amazon Corretto 11
No Java at all

I had a similar message when trying to open `SpWizard`

![Screen Shot 2020-04-10 at 1 18 38 PM](https://user-images.githubusercontent.com/40512816/79013767-08d3d080-7b2f-11ea-9607-36400688d2b8.png)

Tested in macOS 10.15 (Catalina)

**Comment by timo11** [comment]
I removed 'at least' from the localization for AppleJavaMinVersionError. There was nothing for MaxVersion. @maxxxxxdlp did you localize that string for other langs?

**Comment by maxxxxxdlp** [comment]
Done

**Comment by maxxxxxdlp** [comment]
![Capture](https://user-images.githubusercontent.com/40512816/79779777-856d6880-8300-11ea-9657-f0964ee17168.PNG)
Can we also improve this message to mention that only 1.8 is supported?

**Comment by maxxxxxdlp** [comment]
I looked over this issue and a related #613 thread
I think the original issue is fixed now.
The only thing remaining is improving the error message so that it says precisely which Java versions are supported.
More info: https://github.com/specify/specify6/issues/728#issuecomment-616693688

@timo11 can you look into customizing the error message install4j generates?
