### ISSUE TITLE
`Collecting Information` does not have + and - buttons

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#766]
<img width="1007" alt="Screen Shot 2020-05-26 at 7 05 39 PM" src="https://user-images.githubusercontent.com/40512816/82962399-c0a92a00-9f85-11ea-8751-ef56f4a1048c.png">

There are no `+` and `-` buttons available for `Collecting Information` table

<img width="883" alt="82962367-a40cf200-9f85-11ea-8a37-c1f29e81a4b0" src="https://user-images.githubusercontent.com/40512816/82962427-d159a000-9f85-11ea-8975-c5f42c14b03e.png">

The same problem when `Collecting Information` is embedded inside a CO

**Comment by timo11** [comment]
This is the way it is supposed to work for collections with collecting events embedded, which is the default for all or almost all disciplines except fish. However, there seems to be a problem in that it is possible to add ces to an embedded ce collection by opening the ce data form w/o a record set and entering data in the new record that is created . I think the ce form is not on the Data Task by default in embedded ce collections, so that is not likely to happen, but it might have negative consequences because an exact 1-1 relationship between co and ce is assumed in the code.

**Comment by maxxxxxdlp** [comment]
@timo11 ok. I opened #769 for that
