### ISSUE TITLE
Field Notes for English installation are not in English

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#778]
Field Notes for my Specify, which has never been changed to another language are in not English.

**Comment by beach53** [comment]
Never too late to learn another language.


James H. Beach, Executive Director
Specify Collections Consortium
Biodiversity Institute
University of Kansas
1345 Jayhawk Boulevard
Lawrence, KS 66045, USA

beach@specifysoftware.org
www.specifysoftware.org
Office: +1 785.864.4645
Cell: +1 785.331.8508

**Comment by timo11** [comment]
If the database or its ancestors were used during the early to middle stages of the Slavic language story, strange and unexpected things are not surprising, especially If russian and ukrainian are available to select in Preferences. If the database has never been exposed to internal pre 6.8.00 usage then we have problem, and a copy of the db would be useful.

**Comment by timo11** [comment]
This happens for fields (possibly all of them) added to the schema for which russian and ukrainian names were added, because the descriptions were not adjusted to account for the added names. It seems whichever language is defined first in the list of names for the fields is used regardless of the language specify is configured for (though it could be more random than that). In a db I just created with the wizard, fields in AccessionCitation have descriptions in english, portuguese, and russian.

It happens for databases created by the wizard, new collections added to an existing db, and probably after schema updates - still under investigation.

**Comment by timo11** [comment]
I just updated a 6.7.03 db to 6.8 and the field descriptions in the most recently added tables (e.g. taxonattribute, accessioncitation) are in at least three languages. So it's quite possible that all 6.8.00 dbs have this probllem.

**Comment by timo11** [comment]
The tables affected are accessioncitation, extractor, pcrperson, and taxonattribute. I'm not sure if these are all the new tables added since 6.7.04 or just the most recent additions.

There are also fields that were added to pre-existing tables that have descriptions in the wrong language.
