### ISSUE TITLE
Clicking Return Loan button on Loan Form gives blank dialog

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#868]
Open loan form 
Click 'Return Loan' at bottom
this image appears

![116283692-cc7f0c80-a751-11eb-9286-ccaf6cdb30d7](https://user-images.githubusercontent.com/61208178/116285317-a35f7b80-a753-11eb-8805-9dedbde72c7f.png)

**Comment by timo11** [comment]
try using these forms:

[common.views.zip](https://github.com/specify/specify6/files/6387227/common.views.zip)

**Comment by timo11** [comment]
[common.viewsdeaccTheresa.xml.zip](https://github.com/specify/specify6/files/6406990/common.viewsdeaccTheresa.xml.zip)

I can't duplicate the issue using the views Theresa sent me, which I think are what Yvonne was using when the problem was occurring. If the file above works for Yvonne and others now maybe it is a random fluke or fixed by accident situation.

**Comment by yvonneekanim** [comment]
This problem is back but different. This time when I click on 'return loan it works as it should but when I click on 'return preparation' I get the blank dialogue. It is probably a windows issue since it works fine on Norine's mac. Can someone else try to verify this on a windows pc?
