### ISSUE TITLE
Stinkbait?

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#873]
No idea what needs to be tested here or what might be affected. Please help Tim!

**Comment by timo11** [comment]
As of 6/19 or so there is a S2n/Stinkbait/Syftorium prefs panel on the preferences form.
UI adjustments remain to be done.

Clicking Enable registers the current collection. If registration succeeds, the Send button is enabled.
Clicking Send the first time builds a dwc archive containing all records in the collection and sends it to the Syftorium. Subsequent sends only send data added or modified since the last send (deletes not handled yet). 

Still to do:  
add a link to a web page explaining the syftorium. 
Allow users to see what fields are being sent, and perhaps eventually allowing them to withhold lat/long or other data.

**************************************************************************************************

Also, it is possible to view information about the specimen's digital life in a web browser. Currently the only way to do this is to put buttons on dataforms. The commandType should be "DataEntry" and the action can be either "SpiceDigOcc" or "SpiceDigTx". "SpiceDigOcc" will only work on CollectionObject forms, but "SpiceDigTx" buttons will work on CO, Determination, or Taxon forms.
Example form def:
>  <cell type="command" id="syfto" name="SpiceDig" label="Spice Dig" commandtype="DataEntry" action="SpiceDigOcc" ignore="true" initialize="vis=false"/>

**Comment by timo11** [comment]
SN btns show up at right end - alllll the way over - of top form border for CO and Taxon main forms. They don't display on subforms, nor dialogs (eg tree view popups)

**Comment by tlammer** [comment]
the button on the CO form and the option in the taxon pick list both take you to a webpage, so it seems the buttons work

**Comment by timo11** [comment]
Register fails for newly created database.

**Comment by tlammer** [comment]
sent data to specify network.  edited records and added records and it appears to have sent that data as well.  Just need to check newly created databases

**Comment by tlammer** [comment]
Can register a newly created database.  when I click send data it tells me there is nothing to update, which seems fair for this release.
