### ISSUE TITLE
Implement option to create new preparation from disposal form

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#904]
I currently get a 'Specify could not recover from a database update problem' when I create a new preparation from disposal preps

**Comment by norinespears** [comment]
I do not get an exception, but I am unable to edit any of the fields except for 'count'. I can save that but all other fields are blank.

**Comment by timo11** [comment]
I got no exception but with current forms there is no way to link to a preparation. My forms allowed that if you linked to the prep very carefully. Which is why the ''+" button now behaves just like it does for loan preparations.

**Comment by norinespears** [comment]
Disposal Preparations do not behave like Loan Preparations. Perhaps we should understand this better? Here are screenshots:
<img width="1058" alt="Screen Shot 2021-05-18 at 11 16 41 AM" src="https://user-images.githubusercontent.com/61208178/118687834-14caa100-b7cb-11eb-8a93-415e05c1fb86.png">
<img width="1234" alt="Screen Shot 2021-05-18 at 11 17 32 AM" src="https://user-images.githubusercontent.com/61208178/118687839-15633780-b7cb-11eb-8612-b1cff0ecd802.png">
<img width="1117" alt="Screen Shot 2021-05-18 at 11 20 59 AM" src="https://user-images.githubusercontent.com/61208178/118687978-36c42380-b7cb-11eb-986d-351ba85ff8f0.png">
<img width="1100" alt="Screen Shot 2021-05-18 at 11 21 23 AM" src="https://user-images.githubusercontent.com/61208178/118687983-375cba00-b7cb-11eb-8e02-3adfab57c77d.png">

**Comment by norinespears** [comment]
I just tried this and I got all of the dialogs for adding a preparation but then nothing was added to the actual disposal:

opened existing disposal
clicked the '+' sign to add a prep
the 'ask' dialog appeared
I chose Preparation
the Preparation number dialog appeared
I entered a Cat # 
I said save
Nothing happened on the form and the 'save' button was not activated.

In the log file I found this: 17:01:23 ERROR datamodel.busrules.DisposalPreparationBusRules:280 - The Disposal's Multiview should not be null!

**Comment by norinespears** [comment]
The behavior for adding a Disposal Prep is different depending on whether the subform is being viewed in a 'grid' or 'form' format. Here's my story: When I am in an existing Disposal, the disposal prep is in form view and I click on the '+' sign to add a disposal prep I get this dialog:
<img width="1111" alt="Screen Shot 2021-06-28 at 11 37 11 AM" src="https://user-images.githubusercontent.com/61208178/123673326-f1e9ce80-d805-11eb-9d30-0a01cbb336b2.png">



when I am in grid view I get this dialog:

<img width="1138" alt="Screen Shot 2021-06-28 at 11 36 25 AM" src="https://user-images.githubusercontent.com/61208178/123673370-00d08100-d806-11eb-8407-c44140dd27db.png">


Also, if I am in form view and then add a disposal preparation the form does not update (I already had one prep in the disposal, I add another prep in the disposal but it still shows 1). BUT I know that the prep has been added because if I change to the grid view I can see 2 disposal preps and further - if I go back to the form view the second prep is now available. Sorry that the explanation/story was so confusing. I'm happy to make a video.

**Comment by norinespears** [comment]
YESSS!!
