### ISSUE TITLE
Unable to open a Deaccession

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#905]
in latest version (260)/ Deaccession database
I query by deaccession number
several results appear
I double click on any of the records but nothing happens

**Comment by timo11** [comment]
Because Deaccessions were removed from the interactions task bar, they can no longer be opened from query results, which there is no longer a button to show them in form view on the query results table. Code was written to allow display in forms other than those on the side bar - mostly motivated by the need to show preparation results in a form, but was removed after discussing the feature in a meeting.
